name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      NEW_RELIC_API_KEY: ${{ secrets.NEWRELIC_API_KEY }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEWRELIC_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}" -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}"

      - name: Terraform Apply 
        run: |
          terraform apply -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}" -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" -auto-approve 
