name: "Terraform Plan"

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        env:
          NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      
      - name: "Terraform Init"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "~> 2.22.1"
      
      - name: "Terraform Plan"
        id: plan
        run: terraform plan
